server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: account-ws
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka
