spring:
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/home/spark/Documentos/repositorios/spring-cloud/config
        #git:
        #  uri: https://github.com/fabriciolfj/spring-config-server.git
        #  clone-on-start: true
  application:
    name: configServer
server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: "*"
          #- bus-refresh
